# Generated by Django 5.0.6 on 2024-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial =True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('surName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('ID', models.CharField(max_length=20, unique=True)),
                ('Department', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('joinedDate', models.CharField(max_length=20)),
                ('NextofKin', models.CharField(max_length=200)),
                ('NextofKinNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
